/*
 * Copyright (C) F.D. Sattorov Systems, Inc - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by F.D. Sattorov <farrukhjon.sattorov@gmail.com>, May 2016.
 */

package org.farrukh.amazon.products;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vagrant' at '7/25/16 1:16 PM' with Gradle 2.14
 *
 * @author vagrant, @date 7/25/16 1:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
