/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vagrant' at '11/10/15 7:53 PM' with Gradle 2.7
 *
 * @author vagrant, @date 11/10/15 7:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
