/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Farrukhjon' at '12/1/14 11:32 AM' with Gradle 2.2
 *
 * @author Farrukhjon, @date 12/1/14 11:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
