package org.farrukh.groovy.project
/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Farrukhjon' at '10/9/15 12:58 PM' with Gradle 2.5
 *
 * @author Farrukhjon, @date 10/9/15 12:58 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
