CREATE DATABASE IF NOT EXISTS storedb;

USE storedb;

SET foreign_key_checks=0;

DROP TABLE IF EXISTS address;
CREATE TABLE IF NOT EXISTS address (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    country VARCHAR(120),
    region VARCHAR(120),
    city VARCHAR(120),
    street VARCHAR(120),
    phone VARCHAR(120),
    email VARCHAR(120)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS customers;
CREATE TABLE IF NOT EXISTS customers (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    address_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (address_id)
        REFERENCES address (id)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS orders;
CREATE TABLE IF NOT EXISTS orders (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    customer_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (customer_id)
        REFERENCES customers (id)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    number INT,
    price DOUBLE,
    category_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (category_id)
        REFERENCES categories (id)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS product_details;
CREATE TABLE IF NOT EXISTS product_details (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    number INT,
    manufacturer VARCHAR(200)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;


DROP TABLE IF EXISTS categories;
CREATE TABLE IF NOT EXISTS categories (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS payments;
CREATE TABLE IF NOT EXISTS payments (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    order_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (order_id)
        REFERENCES orders (id)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

SET foreign_key_checks=1;
