package org.farrukh.groovy.project
/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Farrukhjon' at '10/9/15 12:58 PM' with Gradle 2.5
 *
 * @author Farrukhjon, @date 10/9/15 12:58 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
