/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Farrukhjon' at '10/9/15 8:25 PM' with Gradle 2.5
 *
 * @author Farrukhjon, @date 10/9/15 8:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
