package org.farrukh.examples.codenarc

/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Farrukhjon' at '10/9/15 4:58 PM' with Gradle 2.5
 *
 * @author Farrukhjon, @date 10/9/15 4:58 PM
 */
/**
 * Simple library.
 */
class Library {

    /**
     * Just returns true.
     * @return true.
     */
    boolean someLibraryMethod() {
        true
    }
}
