logging:
  level:
    org.springframework.jdbc: DEBUG
spring:
  datasource:
            url: jdbc:mysql://localhost:3306/testdb?useSSL=false
            username: root
            password: sa
            driverClassName: com.mysql.jdbc.Driver