# turn on the banner and disable groovy templating
spring:
    main:
        show_banner: true
    groovy:
        template:
            check-template-location: false
    rabbitmq:
        host: rabbitmq
        virtual-host: /
        username: guest
        password: guest
# app specific properties
example-app:
    rabbitChannelCacheSize: 2
    rabbitPrefetchCount: 25
    rabbitQueueName: example-queue
    rabbitExchangeName: example-exchange
    rabbitExchangeDurable: true
    threadPoolSize: 50
