SELECT *
FROM
  (SELECT e.FIRST_NAME,
    MAX(e.SALARY) AS SALARY,
    d.DEPARTMENT_NAME
  FROM EMPLOYEES e
  INNER JOIN DEPARTMENTS d
  ON d.DEPARTMENT_ID = d.DEPARTMENT_ID
  GROUP BY d.DEPARTMENT_NAME,
    e.FIRST_NAME
  )
WHERE ROWNUM <=2;
